# Generated by Django 5.2.4 on 2025-07-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RawWebhookLog',
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='default', max_length=100)),
                ('event_type', models.CharField(blank=True, max_length=200)),
                ('correlation_id', models.CharField(blank=True, max_length=200)),
                ('signature_valid', models.BooleanField(default=False)),
                ('headers', models.JSONField(blank=True, default=dict)),
                ('payload', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
